### ISSUE TITLE
Failed to apply the VCL - Unused sub vcl_synth

### ISSUE THREAD

**Issue by andreasemer** [nexcess/magento-turpentine#1327]
After updateing to the current stable version 0.7.1 and trying to apply the vcl in the backend i got the following error:

`Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Unused sub vcl_synth, defined: ('input' Line 83 Pos 5) sub vcl_synth { ----#########-- Running VCC-compiler failed, exit 1 VCL compilation failed `

If i change the "Fix HTTPS redirect" value to Enabled i get 

`Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Expected return action name. ('input' Line 92 Pos 9) return (synth(750, "")); --------#####----------- Running VCC-compiler failed, exit 1 VCL compilation failed `

After removing the code from the commit https://github.com/nexcess/magento-turpentine/commit/796832e68b482fc8ef3fafcfd4a6d8381f9d5d7c

it works again. 

Magento is 1.9.2.4
Varnish 3.0.7
PHP 7.0.12

Can anyone reproduce this?

**Comment by miguelbalparda** [comment]
@hmphu can you check please?

**Comment by leonpoole** [comment]
@andreasemer Are you using the latest from master or did you download the 0.7.1 files from the 'releases' section? Have a look at issue #1312 - it's very similar to yours. The fix by @hmphu (that is now merge with master in PR #1317 / commit 4929b8a) works perfectly in Varnish 3.0.7 for me.

@miguelbalparda Could you tag a new release of master for 0.7.2?

**Comment by andreasemer** [comment]
@leonpoole That is it right, i haved installed it with composer. 

@miguelbalparda Can you pelase tag a new release for 0.7.2 ?

**Comment by miguelbalparda** [comment]
The 0.7.1 tag should have the latest code, 0.7.2 is still in the make in the devel branch @andreasemer

**Comment by andreasemer** [comment]
@miguelbalparda Sorry, but i think this is not true. I have created a diff from tag 0.7.1 and dev-master, there are several changes. 

Can you please check this again?

**Comment by andreasemer** [comment]
![bildschirmfoto 2016-12-02 um 17 54 46](https://cloud.githubusercontent.com/assets/1199310/20842629/728ffdd8-b8b8-11e6-9ffe-9a3dd697411c.png)

**Comment by miguelbalparda** [comment]
Thanks for the heads up, it seems I didn't remove the tag when I recreated the release after the fix and I end up with a new release with the old code in the tag. Should be updated now [here](https://github.com/nexcess/magento-turpentine/releases/tag/0.7.1).

**Comment by leonpoole** [comment]
@miguelbalparda Thanks, looks good to me :thumbsup:

**Comment by ADDISON74** [comment]
@andreasemer: This is an offtopic question. Are you using Inchoo's extension for making Magento 1 compatible with PHP v7? I am still testing it before going in production with v7, still using v5.5.

**Comment by andreasemer** [comment]
@miguelbalparda This fixed the problem

@ADDISON74 Turpentine is compatible with the Inchoo extension. We have our own "hacked" Magento version of 1.9.2.4 or 1.9.3.1 with several bug fixes, performance optimisations and PHP 7 compatibility. For the PHP 7 part we use most of the code from Inchoo. 

If you use the code of Inchoo, keep track which tag you are using, the 1.9.2.4 tag code is not compatible with 1.9.3.1. PHP 7.1 is working with Magento 1 out of the box, because of http://php.net/manual/de/migration71.deprecated.php Mcrypt, but i think you can use something like https://github.com/phpseclib/mcrypt_compat
